filetype off
let &runtimepath .= ',' . expand('<sfile>:p:h') . '/vader.vim'
let &runtimepath .= ',' . expand('<sfile>:p:h:h')
filetype plugin on
set nomore
set noswapfile
set nosplitright
set nosplitbelow
