name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  release-pr:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/.release-please/config.json
          manifest-file: .github/.release-please/manifest.json
